In [1]:
from quara.objects.composite_system_typical import generate_composite_system
from quara.objects.state_typical import generate_state_from_name
from quara.objects.gate_typical import generate_gate_from_gate_name
from quara.objects.povm_typical import generate_povm_from_name
from quara.objects.mprocess_typical import *
from quara.objects.gate import to_kraus_matrices_from_hs

from qulacs import DensityMatrix, PauliOperator, QuantumGateBase
import qulacs
from qulacs.gate import DenseMatrix, CPTP, Measurement, Instrument, X, Y, Z, P0, P1, H

In [2]:
c_sys = generate_composite_system("qubit", 2)
gate = generate_gate_from_gate_name("cx", c_sys, ids=[0, 1])
print(gate)

Type:
Gate

Dim:
4

HS:
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0. 

In [27]:
c_sys = generate_composite_system("qubit", 1)
print(get_mprocess_names_type1())
mp = generate_mprocess_from_name(c_sys, "z-type1")
print(mp.hss)
print(mp.dim)
print(mp.to_kraus_matrices(0))
print(mp.to_kraus_matrices(1))
np.log2(2)

['x-type1', 'y-type1', 'z-type1', 'bell-type1', 'z3-type1', 'z2-type1']
[array([[0.5, 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.5]]), array([[ 0.5,  0. ,  0. , -0.5],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [-0.5,  0. ,  0. ,  0.5]])]
2
[array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])]
[array([[0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])]


1.0

In [5]:
from qulacs.gate import AmplitudeDampingNoise
target = 0
damping_rate = 0.1
a = AmplitudeDampingNoise(target, damping_rate)
print(a.__class__)

<class 'qulacs.QuantumGateBase'>


In [7]:
print(gate.dim)
kraus_gate = gate.to_kraus_matrices()
print(kraus_gate)


from qulacs.gate import merge,CPTP, P0,P1

gate00 = merge(P0(0),P0(1))
gate01 = merge(P0(0),P1(1))
gate10 = merge(P1(0),P0(1))
gate11 = merge(P1(0),P1(1))
print(P1(0).get_matrix())

gate_list = [gate00, gate01, gate10, gate11]

4
[array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])]
[[0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [42]:
from quara.interface.qulacs.conversion import *
c_sys = generate_composite_system("qubit", 2)
state = generate_state_from_name(c_sys, "z0_z0")
povm = generate_povm_from_name("z_z", c_sys)

gate = generate_gate_from_gate_name("swap", c_sys, [0,1])
qulacs_gate = convert_gate_quara_to_qulacs(gate, [0,1])
qulacs_state = convert_state_quara_to_qulacs(state)

print(qulacs_state.get_matrix())
# qulacs_gate.update_quantum_state(qulacs_state)
print(qulacs_state.get_matrix())

qulacs_povm = convert_povm_quara_to_qulacs(povm)
qulacs_povm.update_quantum_state(qulacs_state)
print(qulacs_state.get_matrix())
print(qulacs_state.get_classical_value(0))

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
0


# Debug

In [4]:
from quara.objects.composite_system_typical import generate_composite_system
from quara.objects.state_typical import generate_state_from_name
from quara.objects.gate_typical import generate_gate_from_gate_name
from quara.objects.povm_typical import generate_povm_from_name
from quara.objects.mprocess_typical import *
from quara.objects.gate import to_kraus_matrices_from_hs

from qulacs import DensityMatrix, PauliOperator, QuantumGateBase
import qulacs
from qulacs.gate import DenseMatrix, CPTP, Measurement, Instrument, X, Y, Z, P0, P1, H
from quara.interface.qulacs.conversion import *

c_sys = generate_composite_system("qubit", 2)
state = generate_state_from_name(c_sys, "z0_x0")

qulacs_density_mat = convert_state_quara_to_qulacs(state)
print(qulacs_density_mat.get_matrix())
state = convert_state_qulacs_to_quara(qulacs_density_mat, c_sys)
print(state)
print(state.to_density_matrix())

[[0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]
Type:
State

Dim:
4

Vec:
[0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0.  0. ]
[[0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]


In [19]:
from quara.objects.composite_system_typical import generate_composite_system
from quara.objects.state_typical import generate_state_from_name
from quara.objects.gate_typical import generate_gate_from_gate_name
from quara.objects.povm_typical import generate_povm_from_name
from quara.objects.mprocess_typical import *
from quara.objects.gate import to_kraus_matrices_from_hs

from qulacs import DensityMatrix, PauliOperator, QuantumGateBase
import qulacs
from qulacs.gate import DenseMatrix, CPTP, Measurement, Instrument, X, Y, Z, P0, P1, H
from quara.interface.qulacs.conversion import *
c_sys = generate_composite_system("qubit", 2)
s = generate_state_from_name(c_sys, "z0_x0")
g = generate_gate_from_gate_name("swap", c_sys, [0,1])
state = convert_state_quara_to_qulacs(s)
gate = convert_gate_quara_to_qulacs(g, [0, 1])
gate.update_quantum_state(state)
s = convert_state_qulacs_to_quara(state, c_sys)
print(s.to_density_matrix())
print(generate_state_from_name(c_sys, "x0_z0").to_density_matrix())


[[0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]
[[0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]


In [5]:
from quara.objects.operators import compose_qoperations
from quara.objects.state_typical import generate_state_from_name
from quara.objects.gate_typical import generate_gate_from_gate_name
from quara.objects.composite_system_typical import generate_composite_system
c_sys = generate_composite_system("qubit", 2)
state = generate_state_from_name(c_sys, "z0_x0")
gate = generate_gate_from_gate_name("swap", c_sys)
qoperator = compose_qoperations(gate, state)
print(state.to_density_matrix())
print(qoperator.to_density_matrix())
from quara.objects.gate_typical import get_gate_names_2qubit
get_gate_names_2qubit()

[[0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0.5+0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]
[[0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0. +0.j 0.5+0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]]


['cx', 'cz', 'swap', 'zx90', 'zz90']

In [9]:
from itertools import product
list(range(10))
list(product(["z0", "x0", "y0"], ["toffoli"]))

[('z0', 'toffoli'), ('x0', 'toffoli'), ('y0', 'toffoli')]

In [11]:
from quara.objects.composite_system_typical import generate_composite_system
from quara.objects.state_typical import generate_state_from_name
from quara.objects.gate_typical import generate_gate_from_gate_name
from quara.objects.povm_typical import generate_povm_from_name
from quara.objects.mprocess_typical import *
from quara.objects.gate import to_kraus_matrices_from_hs
from quara.objects.operators import compose_qoperations

from qulacs import DensityMatrix, PauliOperator, QuantumGateBase
import qulacs
from qulacs.gate import DenseMatrix, CPTP, Measurement, Instrument, X, Y, Z, P0, P1, H
from quara.interface.qulacs.conversion import *
c_sys = generate_composite_system("qubit", 1)
mp = generate_mprocess_from_name(c_sys, "z-type2")
ins, indices = convert_instrument_quara_to_qulacs(mp, [0])
print(indices)
state = generate_state_from_name(c_sys, "y0")
num0 = 0
for _ in range(1000):
    density_matrix = convert_state_quara_to_qulacs(state)
    ins.update_quantum_state(density_matrix)
    if density_matrix.get_classical_value(0) == 0:
        num0 = num0+1
print([num0/1000, 1-num0/1000])
density_matrix = convert_state_quara_to_qulacs(state)
ins.update_quantum_state(density_matrix)
print(density_matrix)

[0, 1]
[0.502, 0.498]
 *** Density Matrix ***
 * Qubit Count : 1
 * Dimension   : 2
 * Density matrix : 
(1,0) (0,0)
(0,0) (0,0)



In [2]:
mp.hs(0)

array([[0.5, 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.5]])

In [3]:
from quara.objects.mprocess_typical import get_mprocess_names_type1, get_mprocess_names_type2
print(get_mprocess_names_type2())
c_sys = generate_composite_system("qubit", 1)
mp = generate_mprocess_from_name(c_sys, "z-type2")

['x-type2', 'y-type2', 'z-type2', 'z3-type2', 'z2-type2']


In [4]:
from quara.interface.qulacs.conversion import *
get_index_tuple_from_kraus_matrices_indices(1, [4, 4, 4])

(0, 1)